# mk/mbt.mk -- cc370 toolchain build system for mbt v2
#
# All mvslovers projects use the same 2-line Makefile:
#
#   MBT_ROOT := mbt
#   include $(MBT_ROOT)/mk/mbt.mk
#
# Project configuration lives in project.toml.
# Build runs entirely on the host via cc370/as370/ld370.

# -- Paths ---------------------------------------------------------
MBT_SCRIPTS := $(MBT_ROOT)/scripts
MBT_INCLUDE := $(MBT_ROOT)/include
BUILDDIR    ?= build
DISTDIR     ?= dist

# -- Toolchain defaults --------------------------------------------
# GNU Make pre-defines CC/AS/LD/AR (origin "default"), so a plain ?=
# would NOT override them -- the build would silently run the host's
# cc/as/ld/ar instead of the cc370 cross-toolchain.  Override the
# built-in defaults (and the undefined case) but still honour an
# explicit value from the environment or command line.
ifneq ($(filter undefined default,$(origin CC)),)
CC := cc370
endif
ifneq ($(filter undefined default,$(origin AS)),)
AS := as370
endif
ifneq ($(filter undefined default,$(origin LD)),)
LD := ld370
endif
ifneq ($(filter undefined default,$(origin AR)),)
AR := ar370
endif
FILE370 ?= file370

# ':=' (not '?=') so a host CFLAGS/ASFLAGS/LDFLAGS in the environment does
# NOT leak into the cross-build (e.g. a Homebrew LDFLAGS=-L.../libiconv).
# A 'make CFLAGS=...' on the command line still overrides these.
CFLAGS  := -O1
ASFLAGS :=
LDFLAGS :=

# -- Verbosity -----------------------------------------------------
# 'VERBOSE=1 make' echoes every cc370/as370/ld370/ar370 invocation with
# its full arguments instead of the short [tool] labels, and passes
# --verbose down to the deploy script.
ifeq ($(VERBOSE),1)
  Q :=
  E := @:
  VFLAG := --verbose
else
  Q := @
  E := @echo
  VFLAG :=
endif

# -- Sysroot (libc370 headers/libs/macros) -------------------------
# cc370 locates its own headers/libs relative to its binary
# (<bindir>/../cc370), so derive the sysroot the same way.  Note:
# 'cc370 -print-search-dirs' reports the configure-time install prefix,
# which is wrong for a relocated toolchain -- don't rely on it.
CC_BIN := $(shell command -v $(CC) 2>/dev/null)
ifneq ($(CC_BIN),)
  SYSROOT := $(abspath $(dir $(CC_BIN))/../cc370)
endif
# Fall back to the default install location if the derived sysroot does
# not actually contain the crt objects.
ifeq ($(wildcard $(SYSROOT)/lib/crt0.o),)
  SYSROOT := $(HOME)/.local/cc370
endif

CRT0 := $(SYSROOT)/lib/crt0.o
CRT1 := $(SYSROOT)/lib/crt1.o
CRTM := $(SYSROOT)/lib/crtm.o

# ld370 has no built-in library search path, so the sysroot lib dir must
# be passed explicitly for -lc (libc370) to resolve.
LDLIBDIR := -L$(SYSROOT)/lib

# -- Read project.toml -> .mbt/config.mk --------------------------
$(shell mkdir -p .mbt $(BUILDDIR))
$(shell python3 $(MBT_SCRIPTS)/mbtconfig.py \
    --project project.toml --builddir $(BUILDDIR) \
    --output file 2>&1 | grep -v '^\[mbt\]' >&2)

-include .mbt/config.mk

# -- Dependency artifacts (staged by 'make deps' into .mbt/deps) ----
# Each dep is .mbt/deps/<repo>/{include,lib}: add its headers to the
# compile include path and its archive(s) to the link.
DEP_INCLUDES := $(addprefix -I ,$(wildcard .mbt/deps/*/include))
DEP_LIBS     := $(wildcard .mbt/deps/*/lib/*.a)
CFLAGS       += $(DEP_INCLUDES)

# mbt's own headers (mbtcheck.h test convention) -- always on the include path
# so tests can '#include <mbtcheck.h>'; harmless for sources that don't.
CFLAGS       += -I $(MBT_INCLUDE)

# -- Build provenance (.mbt/buildstamp.h) --------------------------
# Generated by the mbtconfig call above: MBT_PROJECT / MBT_VERSION /
# MBT_COMMIT / MBT_COMMIT_DIRTY, for a banner that names the exact build
# ('#include <buildstamp.h>').  Passing the commit as a -DCOMMIT cflag
# instead would bake it into an object make has no reason to recompile, so
# a build made after a commit would still print the previous hash (#59).
#
# No object needs an explicit prerequisite on it: -MMD lists every -I header
# a TU actually included, so the .d files already make exactly the including
# objects depend on it -- and mbtconfig rewrites it only when a value really
# changed, so an unchanged commit recompiles nothing.  (-MP keeps a wiped
# .mbt/ from wedging the next build.)  Last on the include path, so a
# project's own buildstamp.h would shadow this one.
CFLAGS       += -I .mbt

# -- VPATH for source discovery ------------------------------------
vpath %.c $(SRC_DIRS)
vpath %.asm $(SRC_DIRS)
vpath %.s $(SRC_DIRS)

# -- Header dependency tracking ------------------------------------
# cc370 (-MMD -MP) writes a .d file listing each object's header
# prerequisites, so editing a header rebuilds the dependent objects.
# The source/member names contain '#' (MVS member convention), which
# make treats as a comment -- cc370 does NOT escape it in the .d, so
# the recipe post-processes each .d to escape every '#'.
DEPFLAGS := -MMD -MP

# -- Pattern rules -------------------------------------------------
# A failed recipe must not leave its target behind. as370 writes its object deck
# even when it flags the assembly, so without this a build that stopped at RC 8
# leaves a .o that is NEWER than its source -- and the next `make` calls it up to
# date, links it, and exits 0. Demonstrated: a module whose comment card ate a
# statement fails the build once, then "succeeds" on the second invocation with
# the deck that is missing the statement.
.DELETE_ON_ERROR:

$(BUILDDIR)/%.o: %.c
	$(E) "[cc370] $<"
	$(Q)$(CC) $(CFLAGS) $(DEPFLAGS) -c $< -o $@
	$(Q)d="$@"; d="$${d%.o}.d"; sed 's/#/\\#/g' "$$d" > "$$d.e" && mv "$$d.e" "$$d"

# as370 returns IFOX00's severity as its exit status -- 0 clean, 4 warning,
# 8 error, 12 severe, 16 terminal -- and a warned assembly still punches its
# deck. On MVS that was COND=(8,LT): the ASM step returned 4 and the linkage
# editor ran anyway. make stops on any non-zero status, so a single warned card
# would fail a build over a diagnostic the assembler itself considers survivable.
# The rules below keep RC < 8 and re-raise anything at or above 8 with its own
# code; either way as370's diagnostics have already gone to stderr.
$(BUILDDIR)/%.o: %.asm
	$(E) "[as370] $<"
	$(Q)$(AS) $(ASFLAGS) -o $@ $< || { rc=$$?; [ $$rc -lt 8 ] || exit $$rc; }

$(BUILDDIR)/%.o: %.s
	$(E) "[as370] $<"
	$(Q)$(AS) $(ASFLAGS) -o $@ $< || { rc=$$?; [ $$rc -lt 8 ] || exit $$rc; }

# -- Link helpers --------------------------------------------------
# Called by the generated module rules below.
# $(1) = entry, $(2) = name, $(3) = objects, $(4) = AC, $(5) = norent, $(6) = noreus
# AC/norent/noreus are passed by VALUE (looked up by the make-safe key in the
# rule) so they resolve even for a module name carrying '#'.
#
# $(LIBC_FIRST) is empty for modules and '-lc' for tests (set as a
# target-specific variable on TEST_IMGS below).  crt0/crt1/crtm all declare
# @@START as an unresolved ER, so autocall takes it from whichever archive
# comes first: a dependency that exports @@START (httpd's CGI launcher) wins
# over libc370 and the module runs as a CGI, exiting CC 12 before main().
# Modules keep that behaviour on purpose -- CGI modules need the dependency's
# @@START -- but tests must always get libc370's batch startup.  libc is then
# named twice (first for @@START, last so the dependencies' own libc
# references still resolve); ld370 handles the repeat without complaint.

define LINK_CRT0
	$(E) "[ld370] $(2) (entry=$(1), crt0)"
	$(Q)$(LD) $(LDFLAGS) $(LDLIBDIR) -e $(1) $(CRT0) $(3) $(INTERNAL_ARCHIVE) $(LIBC_FIRST) $(DEP_LIBS) -lc $(if $(4),--ac $(4) ,)$(if $(5),--norent ,)$(if $(6),--noreus ,)-iebcopy -o $(BUILDDIR)/$(2)
endef

define LINK_CRT1
	$(E) "[ld370] $(2) (entry=$(1), crt1)"
	$(Q)$(LD) $(LDFLAGS) $(LDLIBDIR) -e $(1) $(CRT1) $(3) $(INTERNAL_ARCHIVE) $(LIBC_FIRST) $(DEP_LIBS) -lc $(if $(4),--ac $(4) ,)$(if $(5),--norent ,)$(if $(6),--noreus ,)-iebcopy -o $(BUILDDIR)/$(2)
endef

define LINK_CRTM
	$(E) "[ld370] $(2) (entry=$(1), crtm)"
	$(Q)$(LD) $(LDFLAGS) $(LDLIBDIR) -e $(1) $(CRTM) $(3) $(INTERNAL_ARCHIVE) $(LIBC_FIRST) $(DEP_LIBS) -lc $(if $(4),--ac $(4) ,)$(if $(5),--norent ,)$(if $(6),--noreus ,)-iebcopy -o $(BUILDDIR)/$(2)
endef

define LINK_NOCRT
	$(E) "[ld370] $(2) (entry=$(1), no crt)"
	$(Q)$(LD) $(LDFLAGS) $(LDLIBDIR) -e $(1) $(3) $(INTERNAL_ARCHIVE) $(LIBC_FIRST) $(DEP_LIBS) -lc $(if $(4),--ac $(4) ,)$(if $(5),--norent ,)$(if $(6),--noreus ,)-iebcopy -o $(BUILDDIR)/$(2)
endef

# -- Auto-generate link rules for each module/test ----------------
# Each module links to a per-module IEBCOPY unload (build/NAME.iebcopy):
# unlike a bare load module it carries the PDS2 directory (entry point +
# module length), so 'deploy' can ld370 --pack them into one LINKLIB XMIT.
# For each MODULE and TEST, create:
#   build/NAME.iebcopy: build/obj1.o build/obj2.o ...
#       $(call LINK_xxx, ENTRY, NAME, $^, AC, NORENT, NOREUS)
#   name (lowercase): build/NAME.iebcopy    <- alias

# $(1) is the make-safe key; the real member name is MODULE_$(1)_NAME (may
# contain national chars like '#').  The '#' only ever reaches a target/recipe
# via variable expansion -- after comment stripping -- so it stays literal.
define _MODULE_RULE
$(BUILDDIR)/$$(MODULE_$(1)_NAME).iebcopy: $$(MODULE_$(1)_OBJS) $(INTERNAL_ARCHIVE)
	$$(call $$(MODULE_$(1)_LINK_CMD),$$(MODULE_$(1)_ENTRY),$$(MODULE_$(1)_NAME),$$(MODULE_$(1)_OBJS),$$(MODULE_$(1)_AC),$$(MODULE_$(1)_NORENT),$$(MODULE_$(1)_NOREUS))

.PHONY: $$(MODULE_$(1)_ALIAS)
$$(MODULE_$(1)_ALIAS): $(BUILDDIR)/$$(MODULE_$(1)_NAME).iebcopy
endef

$(foreach m,$(MODULES),$(eval $(call _MODULE_RULE,$(m))))
$(foreach t,$(TESTS),$(eval $(call _MODULE_RULE,$(t))))

# -- Per-module IEBCOPY unload lists -------------------------------
MODULE_IMGS := $(foreach m,$(MODULES),$(BUILDDIR)/$(MODULE_$(m)_NAME).iebcopy)
TEST_IMGS   := $(foreach t,$(TESTS),$(BUILDDIR)/$(MODULE_$(t)_NAME).iebcopy)

# Tests link libc370 first so they get its @@START, never a dependency's
# (see the LINK_* helpers above).  Modules are left untouched.
$(TEST_IMGS): LIBC_FIRST := -lc

# -- Include generated header dependencies -------------------------
# Missing on the first build (-include ignores them); present and
# escaped after each object compiles.
-include $(ALL_OBJS:.o=.d)

# -- libc370 in the sysroot vs. [toolchain] ------------------------
# A project pinning '[toolchain] libc370 = "X.Y.Z"' states which runtime it
# is built with: release.yml checks out that tag, and a working copy must
# hold at least it.  Compiling against an older libc than the release will
# link is how a "works here" build turns into a broken load module.
#
# An order-only prerequisite on every object, so it runs before any compile
# (also under -j) but is not a reason to recompile.  The stamp depends on
# libc.a and project.toml, so the check runs on a sysroot reinstall or a
# changed declaration and is otherwise free -- and never on clean/help/doctor,
# which build no objects.  A project with no [toolchain] gets no check at all.
LIBC_STAMP := .mbt/libc370-checked

$(LIBC_STAMP): $(SYSROOT)/lib/libc.a project.toml
	$(Q)python3 $(MBT_SCRIPTS)/mbttoolchain.py --check \
	    --project project.toml --sysroot $(SYSROOT)
	$(Q)touch $@

$(ALL_OBJS): | $(LIBC_STAMP)

# -- Library target ------------------------------------------------
# A [lib] with compiled members produces a static archive (build/<name>.a).
# A [lib] with only `headers` and no `sources` is a *headers-only* export --
# the public API is reached at runtime (e.g. a callback table the host fills
# in), so consumers compile against the headers but link nothing.  No archive
# is built or shipped in that case; LIB_FILE stays empty.
ifdef LIB_NAME
ifneq ($(strip $(LIB_OBJS)),)
LIB_FILE := $(BUILDDIR)/$(LIB_NAME).a

$(LIB_FILE): $(LIB_OBJS)
	$(E) "[ar370] $(LIB_NAME).a ($(words $^) objects)"
	$(Q)$(AR) rc $@ $^
endif
endif

# -- Internal autocall archive -------------------------------------
# Project-private archive of all shared objects (from [internal] sources).
# Every module/test autocalls it (added to the LINK_* command line), so a
# module need only list its own root source(s) and the linker pulls the
# shared rest by autocall.  Not a deliverable -- never packaged or shipped.
ifdef INTERNAL_ARCHIVE
$(INTERNAL_ARCHIVE): $(INTERNAL_OBJS)
	$(E) "[ar370] $(notdir $(INTERNAL_ARCHIVE)) ($(words $^) objects)"
	$(Q)$(AR) rc $@ $^
endif

# -- Standard targets ----------------------------------------------
# Bare `make` builds the project's PRIMARY deliverable; `make all` builds
# everything it declares.  Driven by [project] type:
#   library             -> primary = the static archive (no load modules)
#   application/runtime -> primary = the load modules; `all` adds [lib]
# Set the default goal explicitly here -- the per-module rules above are
# generated via $(eval) inside a foreach, so the first one (e.g.
# build/UFSD.iebcopy) would otherwise become the default goal.
ifeq ($(PROJECT_TYPE),library)
.DEFAULT_GOAL := lib
ALL_PREREQS   := lib
else
.DEFAULT_GOAL := modules
ALL_PREREQS   := modules $(if $(LIB_NAME),lib)
endif

.PHONY: all modules test test-mvs test-host check lib package dist deps deploy doctor compiledb release \
        prerelease clean distclean help

# Help
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Build:"
	@echo "  (bare make)  Build the primary deliverable for this type"
	@echo "               (library: the archive; else: load modules)"
	@echo "  all          Build everything (modules + library archive)"
	@echo "  modules      Build production modules only"
	@echo "  test         Build test modules"
	@echo "  lib          Build library archive"
	@echo ""
	@echo "Modules:"
	@$(foreach m,$(MODULES),echo "  $(MODULE_$(m)_ALIAS)";)
	@echo ""
	@echo "Tests:"
	@$(foreach t,$(TESTS),echo "  $(MODULE_$(t)_ALIAS)";)
	@echo ""
	@echo "Package & Release:"
	@echo "  package      Create release artifacts in dist/"
	@echo "  dist         Re-render the SMP install package alone ([distribution])"
	@echo "  deploy       Upload XMITs to MVS and RECV370"
	@echo "  test-host    Build + run the dual tests natively (fast inner loop)"
	@echo "  test-mvs     Build + deploy test modules + run the suite on MVS"
	@echo "  check        Run every available test suite (host + MVS)"
	@echo "  release      Version bump + git tag + GH release"
	@echo "  prerelease   Prerelease (no version bump)"
	@echo ""
	@echo "Other:"
	@echo "  deps         Download declared dependencies (like old bootstrap)"
	@echo "  doctor       Check toolchain and connectivity"
	@echo "  compiledb    Write compile_commands.json for clangd"
	@echo "  clean        Remove build/ dist/ (keeps staged deps)"
	@echo "  distclean    clean + remove all of .mbt/ (incl. deps)"
	@echo "  help         Show this message"
	@echo ""
	@echo "Options:"
	@echo "  VERBOSE=1    Show full cc370/as370/ld370/ar370 commands"
	@echo "               (e.g. 'VERBOSE=1 make')"

# Build everything the project declares (see ALL_PREREQS above)
all: $(ALL_PREREQS)
	@echo "[mbt] Build complete"

# Build production modules only
modules: $(MODULE_IMGS)
	@echo "[mbt] Modules built: $(words $(MODULES))"

# Build test modules
test: $(TEST_IMGS)
	@echo "[mbt] Tests built: $(words $(TESTS)) module(s)"

# Build library archive (or just report headers for a headers-only [lib])
ifdef LIB_NAME
lib: $(LIB_FILE)
	@echo "[mbt] Library: $(if $(LIB_FILE),$(LIB_FILE),$(LIB_NAME) (headers only, $(words $(LIB_HEADERS)) header(s)))"
else
lib:
	@echo "[mbt] No [lib] section in project.toml"
endif

# -- Packaging -----------------------------------------------------
DIST_PREFIX := $(PROJECT_NAME)-$(PROJECT_VERSION)

# Default LINKLIB DSN embedded in the release XMIT as its RECEIVE restore
# name.  HLQ-free (the downloader supplies their own prefix) and derived
# only from project.toml, so 'make package' works in CI with no MVS config.
LOAD_LINKLIB := $(shell echo $(PROJECT_NAME) | tr '[:lower:]' '[:upper:]').$(PROJECT_VRM).LINKLIB

package: modules $(if $(LIB_NAME),lib)
	@mkdir -p $(DISTDIR)
# Load library XMIT: all modules packed into one LINKLIB via ld370 --pack
# (each build/NAME.iebcopy carries its PDS2 directory), ready to TSO RECEIVE
# on the target.  Skipped for pure-library projects (no [[module]] blocks):
# an empty input list would make ld370 --pack fail and abort the target.
ifneq ($(strip $(MODULES)),)
	@echo "[mbt] Packaging $(DIST_PREFIX)-load.xmit ($(words $(MODULES)) module(s) -> $(LOAD_LINKLIB))"
	$(Q)$(LD) --pack $(MODULE_IMGS) -o $(DISTDIR)/$(DIST_PREFIX)-load -xmit --dsn $(LOAD_LINKLIB)
endif
ifdef LIB_NAME
	@# Library export: headers always; the .a only if the [lib] has members
	@# (a headers-only [lib] ships include/ alone -- see the lib target above).
	@echo "[mbt] Packaging $(DIST_PREFIX)-lib.tar.gz"
	@mkdir -p $(BUILDDIR)/pkg-lib/$(DIST_PREFIX)/include
	$(if $(LIB_FILE),@mkdir -p $(BUILDDIR)/pkg-lib/$(DIST_PREFIX)/lib && cp $(LIB_FILE) $(BUILDDIR)/pkg-lib/$(DIST_PREFIX)/lib/)
	@$(foreach h,$(LIB_HEADERS),cp $(h) $(BUILDDIR)/pkg-lib/$(DIST_PREFIX)/include/;)
	@tar czf $(DISTDIR)/$(DIST_PREFIX)-lib.tar.gz \
	    -C $(BUILDDIR)/pkg-lib $(DIST_PREFIX)
	@rm -rf $(BUILDDIR)/pkg-lib
endif
# SMP4 installation package: the SYSMOD (inline in the install job), the
# allocation job and a zip/tar.gz holding those plus the README and the load
# XMIT built above.  Only for projects that declare a [distribution]; the
# load XMIT must already exist, hence after the block above.
ifdef HAS_DISTRIBUTION
	$(Q)python3 $(MBT_SCRIPTS)/mbtdist.py --project project.toml \
	    --distdir $(DISTDIR) --builddir $(BUILDDIR)
endif
	@echo "[mbt] Package complete -> $(DISTDIR)/"

# -- dist (re-render the SMP package alone) -------------------------
# The inner loop for a samplib or JCL edit: re-runs only the generator, so it
# takes a second instead of re-linking and re-packing.  It reuses the load
# XMIT 'package' left in dist/ and fails with a clear message if there is
# none.  CI and release/prerelease always go through 'package'.
dist:
	@python3 $(MBT_SCRIPTS)/mbtdist.py --project project.toml \
	    --distdir $(DISTDIR) --builddir $(BUILDDIR)

# -- Dependencies (download + stage declared deps into .mbt/deps) ---
# Resolve each [dependencies] entry, download its {repo}-{ver}-lib.tar.gz,
# stage headers + .a into .mbt/deps/<repo>/, and lock the SHA. Run before
# 'make' for projects with dependencies. ARGS=--update re-resolves ranges.
deps:
	@python3 $(MBT_SCRIPTS)/mbtdeps.py --project project.toml $(ARGS)

# -- Deploy (pack built load modules -> XMIT -> MVS -> RECEIVE) ----
# No 'modules' prerequisite on purpose: deploy packs whatever is already
# built in $(BUILDDIR) (so 'make ufsd && make deploy' deploys only UFSD,
# 'make && make deploy' deploys all).
deploy:
	@python3 $(MBT_SCRIPTS)/mbtdeploy.py --project project.toml \
	    --builddir $(BUILDDIR) --ld $(LD) $(VFLAG) $(ARGS)

# -- test-mvs (build test modules, deploy to a TESTLIB, run them on MVS) --
# Depends on 'test' so the modules are current; packs them into a separate
# TESTLIB, generates + submits a runner job (batch + TSO per test), and reports
# a pass/fail matrix.  The production LINKLIB must already be deployed (tests
# LOAD data modules from it) -- the runner fails fast if it is absent.
test-mvs: test
	@python3 $(MBT_SCRIPTS)/mbttest.py --project project.toml \
	    --builddir $(BUILDDIR) --ld $(LD) $(VFLAG) $(ARGS)

# -- test-host (build + run the dual tests natively -- fast inner loop) --
# Compiles every [[test]] whose sources are portable C with the host compiler
# and runs it, gating on the exit code.  No MVS; tests carrying .asm are skipped.
test-host:
	@python3 $(MBT_SCRIPTS)/mbttesthost.py --project project.toml \
	    --builddir $(BUILDDIR) $(VFLAG) $(ARGS)

# -- check (run every available test suite: host first, then MVS) --
check: test-host test-mvs
	@:

# -- Doctor (check toolchain) -------------------------------------
doctor:
	@python3 $(MBT_SCRIPTS)/mbtdoctor.py --project project.toml

# -- compile_commands.json for clangd ------------------------------
compiledb:
	@python3 $(MBT_SCRIPTS)/mbtcompiledb.py --project project.toml

# -- Release management --------------------------------------------
# The build already gates on '>= the declared libc370' (during 'package'
# above); --exact adds a WARNING when the sysroot is newer than the pin, i.e.
# when the artifact CI is about to publish was never built here.  Deliberately
# not an error: these targets only bump/tag/push, release.yml then checks out
# the pin and rebuilds, so the local sysroot never reaches the published
# artifact.  Requiring an exact match would force a sysroot downgrade before
# every release for a mismatch CI catches by itself (#71).
prerelease: package
	@python3 $(MBT_SCRIPTS)/mbttoolchain.py --check --exact \
	    --project project.toml --sysroot $(SYSROOT)
	@python3 $(MBT_SCRIPTS)/mvsrelease.py --project project.toml --prerelease

release: package
	@python3 $(MBT_SCRIPTS)/mbttoolchain.py --check --exact \
	    --project project.toml --sysroot $(SYSROOT)
	@python3 $(MBT_SCRIPTS)/mvsrelease.py --project project.toml \
	    --version $(VERSION) \
	    $(if $(NEXT_VERSION),--next-version $(NEXT_VERSION),)

# -- Clean ---------------------------------------------------------
# clean keeps staged deps (.mbt/deps) so 'make clean && make' does not
# re-fetch; distclean wipes the whole .mbt/ (incl. deps). Neither touches
# mbt.lock -- it is committed source (project root), not a build artifact;
# 'make deps' re-stages from it after distclean.
clean:
	@echo "[mbt] Cleaning..."
	@rm -rf $(BUILDDIR)/ $(DISTDIR)/ .mbt/config.mk .mbt/logs/ $(LIBC_STAMP)

distclean: clean
	@rm -rf .mbt/
