"""Build provenance stamp -- the generated `.mbt/buildstamp.h`.

A project that prints its build identity in a banner ("UFSD 1.1.0-dev
(cd5be7f) STARTING") needs the commit hash at compile time. Injecting it as
a `-DCOMMIT` cflag bakes the value into whichever object holds the banner,
and make recompiles that object only when its source or a tracked header
changes -- so a build made after a commit still carries the *previous* hash
(mbt#59). A stamp whose whole purpose is provenance is then quietly wrong.

mbt writes the stamp into a generated header instead. Two properties make
that correct without giving up incremental builds:

  * it is a **header**, so cc370's `-MMD` dependency tracking records it as
    a prerequisite of exactly the objects that included it -- a new commit
    recompiles the banner TU, not the whole project;
  * it is **written only when its content changes**, so an unchanged commit
    leaves the mtime alone and nothing recompiles at all.

Deliberately absent: a build timestamp. It would differ on every run and so
recompile the including TU forever -- the very thing the content-addressing
above avoids.

Git semantics match what ufsd's `-DCOMMIT` did before this existed:
`--untracked-files=no`, i.e. "dirty" counts *tracked* modifications only
(stray notes and generated files are not a provenance difference), and
outside a git checkout (a source tarball) the hash degrades to `unknown`
rather than failing the build.
"""

import subprocess
from pathlib import Path

STAMP_PATH = Path(".mbt") / "buildstamp.h"

# git must never wedge a build: a hung index lock or a network-backed
# worktree would otherwise stall every `make` at parse time.
GIT_TIMEOUT = 10


def _git(*args: str, cwd=None) -> str | None:
    """Run a git command, returning its stdout, or None on any failure.

    Failure is the normal case outside a checkout (no git, no repo, no
    commits yet) -- it degrades the stamp, it never aborts the build.
    """
    try:
        r = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=GIT_TIMEOUT,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if r.returncode != 0:
        return None
    return r.stdout.strip()


def resolve_commit(cwd=None) -> tuple[str, bool]:
    """Return (short_commit, dirty) for the checkout at `cwd`.

    `cwd` is the project root (make's working directory), so in the usual
    submodule layout this is the *project's* commit, not mbt's.
    Outside a git checkout: ("unknown", False).
    """
    commit = _git("rev-parse", "--short", "HEAD", cwd=cwd)
    if not commit:
        return ("unknown", False)
    status = _git("status", "--porcelain", "--untracked-files=no", cwd=cwd)
    return (commit, bool(status))


def _c_string(value: str) -> str:
    """Quote a value as a C string literal."""
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(project: str, version: str, commit: str, dirty: bool) -> str:
    """Render the buildstamp header source."""
    stamp = f"{commit}-dirty" if dirty else commit
    return f"""\
/* buildstamp.h -- auto-generated by mbt.  Do not edit, do not commit.
 *
 * Build provenance for this project.  On the include path as <buildstamp.h>
 * (mk/mbt.mk adds -I .mbt), so a banner can carry the exact build it is:
 *
 *     #include <buildstamp.h>
 *     printf("%s %s (%s)\\n", MBT_PROJECT, MBT_VERSION, MBT_COMMIT);
 *
 * Regenerated at every `make`, but rewritten only when a value actually
 * changed -- an unchanged commit recompiles nothing.  Carries no build
 * timestamp on purpose: that would differ every run.
 */
#ifndef MBT_BUILDSTAMP_H
#define MBT_BUILDSTAMP_H

#define MBT_PROJECT      {_c_string(project)}
#define MBT_VERSION      {_c_string(version)}

/* Short commit of the project checkout, with a "-dirty" suffix when the tree
 * has uncommitted *tracked* changes; "unknown" outside a git checkout.
 * MBT_COMMIT_DIRTY is the same signal as 0/1 for code that reports it
 * separately (a warning line rather than a suffix). */
#define MBT_COMMIT       {_c_string(stamp)}
#define MBT_COMMIT_DIRTY {1 if dirty else 0}

#endif /* MBT_BUILDSTAMP_H */
"""


def write_if_changed(path: Path, content: str) -> bool:
    """Write `content` to `path` only if it differs. True if written.

    This is the load-bearing half of the design: rewriting unconditionally
    (as `.mbt/config.mk` does) would touch the mtime on every `make` and
    recompile the including TU every time.
    """
    try:
        if path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass                        # missing or unreadable -> (re)write it
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def generate(project: str, version: str, path: Path = STAMP_PATH,
             cwd=None) -> bool:
    """Resolve the stamp and write the header. True if it changed."""
    commit, dirty = resolve_commit(cwd)
    return write_if_changed(Path(path), render(project, version, commit, dirty))
