"""Lockfile management.

The lockfile pins exact dependency versions for
reproducible builds. Format:

    [metadata]
    generated   = "2026-03-04T10:30:00Z"
    mbt_version = "1.0.0"

    [dependencies]
    "mvslovers/crent370" = "1.0.0"
"""

import tomllib
from pathlib import Path
from dataclasses import dataclass
from datetime import datetime, timezone

LOCKFILE_PATH = Path(".mbt") / "mvs.lock"


@dataclass
class Lockfile:
    """Parsed lockfile."""
    generated: str
    mbt_version: str
    dependencies: dict[str, str]  # {"owner/repo": "exact_version"}

    @classmethod
    def load(cls, path: Path = LOCKFILE_PATH) -> "Lockfile | None":
        """Load lockfile. Returns None if not found."""
        if not path.exists():
            return None
        try:
            with open(path, "rb") as f:
                data = tomllib.load(f)
        except Exception:
            return None
        meta = data.get("metadata", {})
        return cls(
            generated=meta.get("generated", ""),
            mbt_version=meta.get("mbt_version", ""),
            dependencies=dict(data.get("dependencies", {})),
        )

    def save(self, path: Path = LOCKFILE_PATH) -> None:
        """Write lockfile as TOML.

        Creates parent directories if needed.
        Includes header comment: AUTO-GENERATED — DO NOT EDIT
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# .mbt/mvs.lock",
            "# AUTO-GENERATED by mbt bootstrap — DO NOT EDIT",
            "",
            "[metadata]",
            f'generated   = "{self.generated}"',
            f'mbt_version = "{self.mbt_version}"',
            "",
            "[dependencies]",
        ]
        for dep, ver in sorted(self.dependencies.items()):
            lines.append(f'"{dep}" = "{ver}"')
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    @classmethod
    def create(cls, dependencies: dict[str, str],
               mbt_version: str) -> "Lockfile":
        """Create new lockfile with current timestamp."""
        generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        return cls(
            generated=generated,
            mbt_version=mbt_version,
            dependencies=dependencies,
        )
