//*-----------------------------------------------------------
//* Assemble + NCAL: $MEMBER
//*-----------------------------------------------------------
//ASM$SEQ  EXEC PGM=IFOX00,
//          PARM='DECK,LIST,NOLOAD,TERM,XREF(SHORT),RENT'
$SYSLIB_CONCAT
//SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSPUNCH DD DSN=$PUNCH_DSN($MEMBER),DISP=SHR
//SYSTERM  DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//SYSGO    DD DUMMY
//SYSIN    DD DSN=$SOURCE_DSN($MEMBER),DISP=SHR
//LNK$SEQ  EXEC PGM=IEWL,PARM='NCAL,LIST,XREF,LET,RENT',
//          COND=(4,LT,ASM$SEQ)
//SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSPRINT DD SYSOUT=*
//SYSLMOD  DD DSN=$NCALIB_DSN($MEMBER),DISP=SHR
//SYSLIN   DD DSN=$PUNCH_DSN($MEMBER),DISP=SHR
